// src/lib/mockData.ts
// Mock data for testing Hotel Grader 40-Point Audit UI
// Created: November 16, 2025

import type { AuditReport } from '@/types/audit';

export const MOCK_AUDIT_REPORT: AuditReport = {
  hotelId: 'mock-hotel-123',
  hotelName: 'Grand Plaza Hotel',
  city: 'Chicago',
  state: 'IL',
  address: '123 Michigan Ave, Chicago, IL 60601',
  
  executiveSummary: {
    overallScore: 78,
    overallGrade: 'B+',
    competitiveRank: 3,
    competitiveTotal: 12,
    strengths: [
      'Google Business Profile optimization',
      'Strong online reputation (4.6★)',
      'Active social media presence',
    ],
    criticalIssues: [
      'Website performance below industry standards',
      'Limited metasearch visibility',
      'Inconsistent review response rate',
    ],
    keyFinding: 'Your hotel ranks #3 of 12 competitors with strong reviews but significant untapped potential in direct booking optimization. Improving website speed and metasearch presence could increase direct revenue by 15-25%.',
  },
  
  digitalPresence: {
    score: 72,
    color: 'amber',
    isLocked: false,
    googleBusinessProfile: {
      score: 88,
      color: 'green',
      label: 'Google Business Profile',
      value: '88/100',
      insight: 'Well-optimized with 120+ photos and regular updates.',
      recommendation: 'Add virtual tour and more interior photos.',
    },
    websitePerformance: {
      score: 62,
      color: 'amber',
      label: 'Website Performance',
      value: '3.2s load time',
      insight: 'Mobile load time exceeds recommended 2 seconds.',
      recommendation: 'Compress images and enable caching (could boost conversions by 18%).',
    },
    searchVisibility: {
      score: 75,
      color: 'green',
      label: 'Search Visibility',
      value: 'Page 1 for 3 keywords',
      insight: 'Ranking for brand + location searches.',
      recommendation: 'Target long-tail keywords like "romantic hotel Chicago".',
    },
    brandProtection: {
      score: null,
      color: 'amber',
      label: 'Brand Protection',
      isLocked: true,
      insight: 'Unlock to see brand mention analysis',
    },
    mobileFriendly: {
      score: null,
      color: 'green',
      label: 'Mobile Experience',
      isLocked: true,
    },
    localSEO: {
      score: null,
      color: 'amber',
      label: 'Local SEO',
      isLocked: true,
    },
    directoryListings: {
      score: null,
      color: 'green',
      label: 'Directory Listings',
      isLocked: true,
    },
    metrics: [
      {
        score: 88,
        color: 'green',
        label: 'Google Business Profile',
        value: '88/100',
        insight: 'Well-optimized with 120+ photos and regular updates.',
        recommendation: 'Add virtual tour and more interior photos.',
      },
      {
        score: 62,
        color: 'amber',
        label: 'Website Performance',
        value: '3.2s load time',
        insight: 'Mobile load time exceeds recommended 2 seconds.',
        recommendation: 'Compress images and enable caching (could boost conversions by 18%).',
      },
      {
        score: 75,
        color: 'green',
        label: 'Search Visibility',
        value: 'Page 1 for 3 keywords',
        insight: 'Ranking for brand + location searches.',
        recommendation: 'Target long-tail keywords like "romantic hotel Chicago".',
      },
      {
        score: null,
        color: 'amber',
        label: 'Brand Protection',
        isLocked: true,
        insight: 'Unlock to see brand mention analysis',
      },
      {
        score: null,
        color: 'green',
        label: 'Mobile Experience',
        isLocked: true,
      },
      {
        score: null,
        color: 'amber',
        label: 'Local SEO',
        isLocked: true,
      },
      {
        score: null,
        color: 'green',
        label: 'Directory Listings',
        isLocked: true,
      },
    ],
  },
  
  reputation: {
    score: 82,
    color: 'green',
    isLocked: false,
    overallRating: {
      score: 92,
      color: 'green',
      label: 'Overall Rating',
      value: '4.6 ★',
      insight: 'Strong rating across all platforms.',
      recommendation: 'Maintain quality and encourage reviews from happy guests.',
    },
    reviewVolume: {
      score: 78,
      color: 'green',
      label: 'Review Volume',
      value: '847 reviews',
      insight: 'Good review volume but competitors averaging 1,200+.',
      recommendation: 'Implement post-stay email campaign (target 50+ reviews/month).',
    },
    reviewRecency: {
      score: 85,
      color: 'green',
      label: 'Review Recency',
      value: '12 in last 30 days',
      insight: 'Consistent recent reviews signal active property.',
    },
    responseRate: {
      score: null,
      color: 'amber',
      label: 'Response Rate',
      isLocked: true,
      insight: 'Unlock to see response analysis',
    },
    sentimentScore: {
      score: null,
      color: 'green',
      label: 'Sentiment Analysis',
      isLocked: true,
    },
    reviewDistribution: {
      score: null,
      color: 'green',
      label: 'Rating Distribution',
      isLocked: true,
    },
    competitivePosition: {
      score: null,
      color: 'green',
      label: 'Competitive Position',
      isLocked: true,
    },
    metrics: [
      {
        score: 92,
        color: 'green',
        label: 'Overall Rating',
        value: '4.6 ★',
        insight: 'Strong rating across all platforms.',
        recommendation: 'Maintain quality and encourage reviews from happy guests.',
      },
      {
        score: 78,
        color: 'green',
        label: 'Review Volume',
        value: '847 reviews',
        insight: 'Good review volume but competitors averaging 1,200+.',
        recommendation: 'Implement post-stay email campaign (target 50+ reviews/month).',
      },
      {
        score: 85,
        color: 'green',
        label: 'Review Recency',
        value: '12 in last 30 days',
        insight: 'Consistent recent reviews signal active property.',
      },
      {
        score: null,
        color: 'amber',
        label: 'Response Rate',
        isLocked: true,
        insight: 'Unlock to see response analysis',
      },
      {
        score: null,
        color: 'green',
        label: 'Sentiment Analysis',
        isLocked: true,
      },
      {
        score: null,
        color: 'green',
        label: 'Rating Distribution',
        isLocked: true,
      },
      {
        score: null,
        color: 'green',
        label: 'Competitive Position',
        isLocked: true,
      },
    ],
  },
  
  socialMedia: {
    score: 65,
    color: 'amber',
    isLocked: false,
    facebookPresence: {
      score: 72,
      color: 'amber',
      label: 'Facebook Presence',
      value: '2,400 followers',
      insight: 'Active page but engagement below industry average.',
      recommendation: 'Post 3-4x per week with guest photos and local events.',
    },
    instagramPresence: {
      score: 68,
      color: 'amber',
      label: 'Instagram Presence',
      value: '1,850 followers',
      insight: 'Good visual content but inconsistent posting.',
      recommendation: 'Daily Stories + 3 feed posts per week with branded hashtag.',
    },
    engagement: {
      score: null,
      color: 'red',
      label: 'Engagement Rate',
      isLocked: true,
    },
    contentQuality: {
      score: null,
      color: 'amber',
      label: 'Content Quality',
      isLocked: true,
    },
    postFrequency: {
      score: null,
      color: 'amber',
      label: 'Post Frequency',
      isLocked: true,
    },
    followerGrowth: {
      score: null,
      color: 'green',
      label: 'Follower Growth',
      isLocked: true,
    },
    metrics: [
      {
        score: 72,
        color: 'amber',
        label: 'Facebook Presence',
        value: '2,400 followers',
        insight: 'Active page but engagement below industry average.',
        recommendation: 'Post 3-4x per week with guest photos and local events.',
      },
      {
        score: 68,
        color: 'amber',
        label: 'Instagram Presence',
        value: '1,850 followers',
        insight: 'Good visual content but inconsistent posting.',
        recommendation: 'Daily Stories + 3 feed posts per week with branded hashtag.',
      },
      {
        score: null,
        color: 'red',
        label: 'Engagement Rate',
        isLocked: true,
      },
      {
        score: null,
        color: 'amber',
        label: 'Content Quality',
        isLocked: true,
      },
      {
        score: null,
        color: 'amber',
        label: 'Post Frequency',
        isLocked: true,
      },
      {
        score: null,
        color: 'green',
        label: 'Follower Growth',
        isLocked: true,
      },
    ],
  },
  
  advertising: {
    score: 58,
    color: 'amber',
    isLocked: false,
    googleAdsPresence: {
      score: 48,
      color: 'red',
      label: 'Google Ads Presence',
      value: 'Not detected',
      insight: 'No paid search campaigns found.',
      recommendation: 'Launch branded + competitor keyword campaigns (ROI typically 3-5x).',
    },
    metaAdsPresence: {
      score: null,
      color: 'red',
      label: 'Meta Ads Presence',
      isLocked: true,
    },
    metasearchVisibility: {
      score: null,
      color: 'red',
      label: 'Metasearch Visibility',
      isLocked: true,
      insight: 'Unlock to see Google Hotel Ads analysis',
    },
    brandProtection: {
      score: null,
      color: 'amber',
      label: 'Brand Protection',
      isLocked: true,
    },
    adSpendEfficiency: {
      score: null,
      color: 'red',
      label: 'Ad Spend Efficiency',
      isLocked: true,
    },
    competitorAdGaps: {
      score: null,
      color: 'amber',
      label: 'Competitor Ad Gaps',
      isLocked: true,
    },
    metrics: [
      {
        score: 48,
        color: 'red',
        label: 'Google Ads Presence',
        value: 'Not detected',
        insight: 'No paid search campaigns found.',
        recommendation: 'Launch branded + competitor keyword campaigns (ROI typically 3-5x).',
      },
      {
        score: null,
        color: 'red',
        label: 'Meta Ads Presence',
        isLocked: true,
      },
      {
        score: null,
        color: 'red',
        label: 'Metasearch Visibility',
        isLocked: true,
        insight: 'Unlock to see Google Hotel Ads analysis',
      },
      {
        score: null,
        color: 'amber',
        label: 'Brand Protection',
        isLocked: true,
      },
      {
        score: null,
        color: 'red',
        label: 'Ad Spend Efficiency',
        isLocked: true,
      },
      {
        score: null,
        color: 'amber',
        label: 'Competitor Ad Gaps',
        isLocked: true,
      },
    ],
  },
  
  booking: {
    score: 75,
    color: 'green',
    isLocked: false,
    otaPresence: {
      score: 85,
      color: 'green',
      label: 'OTA Presence',
      value: 'Listed on 8 platforms',
      insight: 'Strong distribution across major OTAs.',
      recommendation: 'Ensure rate parity and current inventory.',
    },
    bookingDotCom: {
      score: 82,
      color: 'green',
      label: 'Booking.com Profile',
      value: '8.8/10 rating',
      insight: 'Well-optimized with Genius program.',
    },
    expedia: {
      score: null,
      color: 'green',
      label: 'Expedia Profile',
      isLocked: true,
    },
    directBookingFlow: {
      score: null,
      color: 'amber',
      label: 'Direct Booking Flow',
      isLocked: true,
      insight: 'Unlock to see conversion analysis',
    },
    mobileBooking: {
      score: null,
      color: 'green',
      label: 'Mobile Booking',
      isLocked: true,
    },
    paymentOptions: {
      score: null,
      color: 'green',
      label: 'Payment Options',
      isLocked: true,
    },
    cancellationPolicy: {
      score: null,
      color: 'amber',
      label: 'Cancellation Policy',
      isLocked: true,
    },
    metrics: [
      {
        score: 85,
        color: 'green',
        label: 'OTA Presence',
        value: 'Listed on 8 platforms',
        insight: 'Strong distribution across major OTAs.',
        recommendation: 'Ensure rate parity and current inventory.',
      },
      {
        score: 82,
        color: 'green',
        label: 'Booking.com Profile',
        value: '8.8/10 rating',
        insight: 'Well-optimized with Genius program.',
      },
      {
        score: null,
        color: 'green',
        label: 'Expedia Profile',
        isLocked: true,
      },
      {
        score: null,
        color: 'amber',
        label: 'Direct Booking Flow',
        isLocked: true,
        insight: 'Unlock to see conversion analysis',
      },
      {
        score: null,
        color: 'green',
        label: 'Mobile Booking',
        isLocked: true,
      },
      {
        score: null,
        color: 'green',
        label: 'Payment Options',
        isLocked: true,
      },
      {
        score: null,
        color: 'amber',
        label: 'Cancellation Policy',
        isLocked: true,
      },
    ],
  },
  
  competitive: {
    score: 71,
    color: 'amber',
    isLocked: false,
    marketPosition: {
      score: 68,
      color: 'amber',
      label: 'Market Position',
      value: '#3 of 12',
      insight: 'Solid mid-tier position with room to improve.',
      recommendation: 'Focus on unique differentiators to reach #1-2.',
    },
    priceCompetitiveness: {
      score: 75,
      color: 'green',
      label: 'Price Competitiveness',
      value: '$189 average',
      insight: 'Well-positioned at 5% below market leader.',
    },
    amenityComparison: {
      score: null,
      color: 'amber',
      label: 'Amenity Comparison',
      isLocked: true,
    },
    ratingVsCompetitors: {
      score: null,
      color: 'green',
      label: 'Rating vs Competitors',
      isLocked: true,
    },
    uniqueAdvantages: {
      score: null,
      color: 'green',
      label: 'Unique Advantages',
      isLocked: true,
    },
    competitiveThreats: {
      score: null,
      color: 'amber',
      label: 'Competitive Threats',
      isLocked: true,
    },
    metrics: [
      {
        score: 68,
        color: 'amber',
        label: 'Market Position',
        value: '#3 of 12',
        insight: 'Solid mid-tier position with room to improve.',
        recommendation: 'Focus on unique differentiators to reach #1-2.',
      },
      {
        score: 75,
        color: 'green',
        label: 'Price Competitiveness',
        value: '$189 average',
        insight: 'Well-positioned at 5% below market leader.',
      },
      {
        score: null,
        color: 'amber',
        label: 'Amenity Comparison',
        isLocked: true,
      },
      {
        score: null,
        color: 'green',
        label: 'Rating vs Competitors',
        isLocked: true,
      },
      {
        score: null,
        color: 'green',
        label: 'Unique Advantages',
        isLocked: true,
      },
      {
        score: null,
        color: 'amber',
        label: 'Competitive Threats',
        isLocked: true,
      },
    ],
  },
  
  competitors: [
    {
      rank: 1,
      name: 'Renaissance Chicago Downtown',
      rating: 4.7,
      reviewCount: 1243,
      distance: 0.3,
      lat: 41.8855,
      lng: -87.6235,
      placeId: 'ChIJ1234',
      priceLevel: 3,
    },
    {
      rank: 2,
      name: 'Hyatt Centric The Loop',
      rating: 4.6,
      reviewCount: 987,
      distance: 0.5,
      lat: 41.8825,
      lng: -87.6295,
      placeId: 'ChIJ5678',
      priceLevel: 3,
    },
    {
      rank: 3,
      name: 'Grand Plaza Hotel',
      rating: 4.6,
      reviewCount: 847,
      distance: 0,
      lat: 41.8835,
      lng: -87.6245,
      placeId: 'ChIJ9012',
      priceLevel: 3,
    },
    {
      rank: 4,
      name: 'Aloft Chicago Downtown',
      rating: 4.5,
      reviewCount: 765,
      distance: 0.7,
      lat: 41.8845,
      lng: -87.6275,
      placeId: 'ChIJ3456',
      priceLevel: 2,
    },
    {
      rank: 5,
      name: 'Kimpton Gray Hotel',
      rating: 4.5,
      reviewCount: 654,
      distance: 0.4,
      lat: 41.8815,
      lng: -87.6285,
      placeId: 'ChIJ7890',
      priceLevel: 3,
    },
    // Additional competitors locked behind email gate
    {
      rank: 6,
      name: 'Hotel Monaco Chicago',
      rating: 4.4,
      reviewCount: 589,
      distance: 0.6,
      lat: 41.8805,
      lng: -87.6305,
      placeId: 'ChIJ1357',
      priceLevel: 3,
    },
    {
      rank: 7,
      name: 'Virgin Hotels Chicago',
      rating: 4.4,
      reviewCount: 512,
      distance: 0.8,
      lat: 41.8795,
      lng: -87.6315,
      placeId: 'ChIJ2468',
      priceLevel: 3,
    },
    {
      rank: 8,
      name: 'The Gwen Hotel',
      rating: 4.3,
      reviewCount: 445,
      distance: 0.9,
      lat: 41.8785,
      lng: -87.6325,
      placeId: 'ChIJ3579',
      priceLevel: 3,
    },
  ],
  
  actionPlan: [
    {
      priority: 'high',
      category: 'Digital Presence',
      action: 'Optimize website speed and mobile performance',
      impact: 'Could increase conversions by 15-25% and improve SEO',
      effort: 'moderate',
      timeline: '2-4 weeks',
      resources: ['Web developer', 'Image optimization tools', 'CDN service'],
    },
    {
      priority: 'high',
      category: 'Advertising',
      action: 'Launch Google Ads campaigns for brand + competitor keywords',
      impact: 'Expected ROI of 3-5x, capture high-intent searchers',
      effort: 'quick-win',
      timeline: '1-2 weeks',
      resources: ['Google Ads budget ($2,000/month)', 'PPC specialist'],
    },
    {
      priority: 'high',
      category: 'Reputation',
      action: 'Implement systematic review generation campaign',
      impact: 'Increase review volume by 50+ per month, boost SEO',
      effort: 'quick-win',
      timeline: '1 week',
      resources: ['Email automation tool', 'Review templates'],
    },
    {
      priority: 'medium',
      category: 'Social Media',
      action: 'Establish consistent posting schedule across platforms',
      impact: 'Improve engagement by 30-40%, build brand awareness',
      effort: 'moderate',
      timeline: '2-3 weeks',
      resources: ['Social media manager', 'Content calendar', 'Scheduling tool'],
    },
    {
      priority: 'medium',
      category: 'Booking',
      action: 'Simplify direct booking flow and add instant booking',
      impact: 'Reduce OTA dependency, increase direct revenue by 10-15%',
      effort: 'significant',
      timeline: '4-6 weeks',
      resources: ['Booking engine upgrade', 'UX designer', 'Developer'],
    },
    {
      priority: 'low',
      category: 'Competitive',
      action: 'Develop unique package offerings to differentiate from competitors',
      impact: 'Create pricing power, attract specific segments',
      effort: 'moderate',
      timeline: '3-4 weeks',
      resources: ['Revenue manager', 'Marketing team', 'Package partnerships'],
    },
  ],
  
  generatedAt: new Date().toISOString(),
  isFullReportUnlocked: false,
};
