// src/lib/mockData.ts
// Mock data for testing Hotel Grader 40-Point Audit UI
// Created: November 16, 2025

import type { AuditReport } from "@/types/audit";

export const MOCK_AUDIT_REPORT: AuditReport = {
  hotelId: "mock-hotel-123",
  hotelName: "Grand Plaza Hotel",
  city: "Chicago",
  state: "IL",
  address: "123 Michigan Ave, Chicago, IL 60601",

  // Overall scores (required at top level)
  overallScore: 78,
  overallGrade: "B+",

  executiveSummary: {
    overallScore: 78,
    overallGrade: "B+",
    competitiveRank: 3,
    competitiveTotal: 12,
    strengths: [
      "Google Business Profile optimization",
      "Strong online reputation (4.6★)",
      "Active social media presence",
    ],
    criticalIssues: [
      "Website performance below industry standards",
      "Limited metasearch visibility",
      "Inconsistent review response rate",
    ],
    quickWins: [
      "Respond to unanswered reviews (2-hour task)",
      "Optimize website images (4-hour task)",
      "Add virtual tour to Google Business (1-day task)",
    ],
    keyFinding:
      "Your hotel ranks #3 of 12 competitors with strong reviews but significant untapped potential in direct booking optimization. Improving website speed and metasearch presence could increase direct revenue by 15-25%.",
  },

  digitalPresence: {
    score: 72,
    color: "amber",
    isLocked: false,
    metrics: [
      {
        id: "dp_1",
        name: "Google Business Profile",
        title: "Google Business Profile",
        score: 88,
        color: "green",
        label: "Google Business Profile",
        value: "88/100",
        insight: "Well-optimized with 120+ photos and regular updates.",
        recommendation: "Add video content to increase engagement by 40%",
        detailedAnalysis: "Your Google Business Profile is performing well above industry average. You have comprehensive information, regular posts, and strong photo coverage. However, competitors are increasingly using video content which generates 3x more engagement. Your response rate to reviews is excellent at 95%, but response time averages 3 days when best practice is within 24 hours.",
        actionSteps: [
          "Create 2-3 short video tours (30-60 seconds each) of key property features",
          "Set up Google Posts automation for weekly updates about offers/events",
          "Implement 24-hour review response protocol",
          "Add Q&A section addressing top 10 common guest questions"
        ],
        expectedImpact: "Adding video content and improving response times could increase direct calls by 25-30% and boost local search ranking by 2-3 positions within 60 days."
      },
      {
        id: "dp_2",
        name: "Website Performance",
        title: "Website Performance",
        score: 62,
        color: "amber",
        label: "Website Performance",
        value: "3.2s load time",
        insight: "Mobile load time exceeds recommended 2 seconds.",
        recommendation: "Optimize images and enable caching to improve load speed",
        detailedAnalysis: "Your website loads in 4.2 seconds on mobile, which is causing 40% bounce rate before page fully loads. Industry data shows every 1-second delay reduces conversions by 7%. Your desktop performance is acceptable at 2.1 seconds, but 68% of your traffic is mobile. Image optimization alone could save 2.1 seconds. Additionally, you're missing critical speed optimizations like browser caching, CDN, and lazy loading.",
        actionSteps: [
          "Compress and convert images to WebP format (saves ~65% bandwidth)",
          "Enable browser caching (one-time setup, instant improvement)",
          "Implement lazy loading for below-fold images",
          "Consider Cloudflare CDN for static assets (free plan available)",
          "Minify CSS and JavaScript files"
        ],
        expectedImpact: "Reducing load time to under 2 seconds could decrease bounce rate by 25%, increase time-on-site by 35%, and improve conversion rate by 15-20%. Expected revenue impact: $3-5K additional monthly bookings."
      },
      {
        id: "dp_3",
        name: "Search Visibility",
        title: "Search Visibility",
        score: 75,
        color: "green",
        label: "Search Visibility",
        value: "Page 1 for 3 keywords",
        insight: "Ranking for brand + location searches.",
        recommendation: "Target long-tail keywords like 'pet-friendly hotel downtown'",
        detailedAnalysis: "You rank #1 for your brand name and #3-5 for 'hotel [city]' but missing out on 200+ high-intent long-tail searches monthly. Competitors are capturing searches like 'boutique hotel with parking' (450 monthly searches), 'romantic hotel downtown' (320 searches), and 'family hotel with pool' (280 searches). These long-tail keywords convert at 3x higher rate than generic terms.",
        actionSteps: [
          "Identify 20 long-tail keywords relevant to your amenities and location",
          "Create dedicated landing pages for top 5 keyword themes",
          "Optimize existing pages with natural keyword integration",
          "Build internal linking structure to boost page authority",
          "Add schema markup for better rich snippet visibility"
        ],
        expectedImpact: "Capturing even 10% of available long-tail traffic could add 60-80 qualified visitors monthly, generating 15-20 additional bookings worth $4-6K monthly revenue."
      },
      {
        id: "dp_4",
        name: "Brand Protection",
        title: "Brand Protection",
        score: 45,
        color: "red",
        label: "Brand Protection",
        isLocked: true,
        insight: "Competitors bidding on your brand name in paid search.",
        recommendation: "Launch defensive Google Ads campaign immediately",
        detailedAnalysis: "Three competitors are actively bidding on '[Your Hotel Name]' searches, appearing above your organic listing. You're losing an estimated 25-30% of brand searches to competitor ads. Cost to defend: $200-300/month. Cost of doing nothing: $2-3K lost revenue monthly. Your brand search volume is 450 searches/month with 65% booking intent. Competitors are spending $1.50-2.50 per click to steal your customers.",
        actionSteps: [
          "Set up Google Ads brand campaign with exact match keywords (priority: critical)",
          "Bid aggressively on your hotel name ($3-5 per click to guarantee top position)",
          "Use ad extensions to take up maximum screen space",
          "Add negative keywords to prevent wasted spend",
          "Set up conversion tracking to measure ROI",
          "Monitor competitor activity weekly and adjust bids"
        ],
        expectedImpact: "Defensive campaign will recapture 80% of lost brand traffic, preventing $2,000-2,400 monthly revenue loss. ROI: 700-800%. Payback period: immediate."
      },
      {
        id: "dp_5",
        name: "Mobile Experience",
        title: "Mobile Experience",
        score: 58,
        color: "amber",
        label: "Mobile Experience",
        isLocked: true,
        insight: "Mobile booking process has 3 unnecessary steps.",
        recommendation: "Simplify to single-page checkout for mobile users",
        detailedAnalysis: "Your current mobile booking flow requires 5 steps with 12 form fields, when best practice is 3 steps with 6 fields. Each additional step loses 15% of users. Your mobile booking abandonment rate is 72% vs industry average of 45%. Users report frustration with small tap targets, difficult date picker, and confusing payment flow. 68% of abandonments happen at step 3 (room selection).",
        actionSteps: [
          "Redesign room selection page with larger images and clearer pricing",
          "Implement auto-fill for guest information fields",
          "Add Apple Pay and Google Pay one-click options",
          "Increase tap target sizes to minimum 44px (currently 28px)",
          "Replace calendar picker with simpler date selection",
          "Add progress indicator showing completion percentage"
        ],
        expectedImpact: "Reducing abandonment from 72% to 50% would increase mobile bookings by 44%. With 200 monthly mobile booking attempts, that's 44 additional bookings worth $8,800 monthly revenue."
      },
      {
        id: "dp_6",
        name: "Local SEO",
        title: "Local SEO",
        score: 52,
        color: "amber",
        label: "Local SEO",
        isLocked: true,
        insight: "Missing citations on 15 key directories.",
        recommendation: "Complete NAP (Name, Address, Phone) across top 20 directories",
        detailedAnalysis: "Your business information is inconsistent across the web. You're listed on 28 directories but only 13 have correct information. TripAdvisor shows old phone number, Yelp has wrong address format, and 15 major directories have no listing at all. This confuses search engines and hurts local rankings. Competitors with complete citations rank 3-5 positions higher for local searches.",
        actionSteps: [
          "Audit current citations using BrightLocal or Moz Local (free trial)",
          "Fix incorrect listings on TripAdvisor, Yelp, Booking.com",
          "Claim listings on missing directories (Foursquare, Yellow Pages, etc)",
          "Ensure exact NAP consistency across all platforms",
          "Add citations to industry-specific directories (AAA, hotel associations)",
          "Set quarterly reminder to verify citation accuracy"
        ],
        expectedImpact: "Complete, consistent citations could improve local pack ranking by 2-4 positions, increasing visibility for 'hotel near me' searches by 40%. Expected monthly impact: 30-40 additional local search bookings."
      },
      {
        id: "dp_7",
        name: "Photos & Visual Content",
        title: "Photos & Visual Content",
        score: 71,
        color: "green",
        label: "Photos & Visual Content",
        isLocked: true,
        insight: "Strong photo library but missing key room types and amenities.",
        recommendation: "Add professional photos of all room categories and amenities",
        detailedAnalysis: "You have 87 photos across platforms, which is good, but analysis reveals gaps: missing photos of 2 room types (deluxe king, family suite), no gym photos, and limited food/beverage images. Properties with complete visual coverage see 35% higher engagement. Your best photos are 2+ years old - freshness matters. Competitor analysis shows top performers have 120+ recent photos with consistent quality and lighting.",
        actionSteps: [
          "Hire professional photographer for 1-day shoot ($800-1,200)",
          "Prioritize missing room types and amenities (gym, restaurant, lobby)",
          "Capture seasonal/event photos quarterly (fall colors, holiday decor)",
          "Create 360° virtual tours of top 3 room types",
          "Ensure consistent style/lighting across all new photos",
          "Update oldest photos first, then fill gaps"
        ],
        expectedImpact: "Complete photo coverage with professional quality could increase click-through rate by 25%, reduce pre-arrival questions by 40%, and improve booking conversion by 12-15%. Investment ROI: 400-600% within first 90 days."
      },
    ],
  },

  reputation: {
    score: 82,
    color: "green",
    isLocked: false,
    metrics: [
      {
        id: "rep_1",
        name: "Overall Rating",
        title: "Overall Rating",
        score: 92,
        color: "green",
        label: "Overall Rating",
        value: "4.6 ★",
        insight: "Strong rating across all platforms.",
        recommendation: "Maintain quality and encourage reviews from happy guests",
        detailedAnalysis: "Your 4.6-star rating places you in the top 15% of hotels in your market. This strong performance is driven by consistently high marks for cleanliness (4.8), location (4.7), and value (4.5). However, service scores are slightly lower at 4.3, presenting an opportunity for improvement. Guest feedback indicates occasional front desk wait times during peak check-in hours. Maintaining this rating requires ongoing focus on service consistency and proactive issue resolution.",
        actionSteps: [
          "Implement service recovery training for all guest-facing staff",
          "Add second front desk agent during peak hours (4-7pm)",
          "Create guest satisfaction survey at mid-stay for multi-night visitors",
          "Develop staff recognition program tied to guest mentions",
          "Monitor daily feedback and address issues within 24 hours"
        ],
        expectedImpact: "Maintaining 4.6+ rating while improving service to 4.5+ could increase booking conversion by 8-12% and justify 3-5% rate premium. Worth approximately $4-6K additional monthly revenue."
      },
      {
        id: "rep_2",
        name: "Review Volume",
        title: "Review Volume",
        score: 82,
        color: "green",
        label: "Review Volume",
        value: "847 reviews",
        insight: "Receiving 15-20 new reviews monthly, above category average.",
        recommendation: "Implement post-stay email automation to boost to 25+ monthly",
        detailedAnalysis: "Your review velocity is good but plateauing. Properties with 25+ monthly reviews see 18% higher conversion rates. You're currently asking for reviews manually, capturing ~40% of guests. Automated post-stay emails capture 60-70% with proper timing and messaging. Your best review sources are Google (45%) and TripAdvisor (35%), but you're underutilizing Booking.com (only 12%).",
        actionSteps: [
          "Set up automated email 3 days post-checkout with review request",
          "Create mobile-optimized review landing page with one-click options",
          "Add QR codes in rooms linking to review pages",
          "Train front desk to mention reviews during checkout",
          "Implement incentive for staff when property reaches review goals"
        ],
        expectedImpact: "Increasing to 25+ monthly reviews could improve conversion rate by 15-18%, worth $4-6K additional monthly revenue. Also improves rankings on all OTA platforms."
      },
      {
        id: "rep_3",
        name: "Review Recency",
        title: "Review Recency",
        score: 91,
        color: "green",
        label: "Review Recency",
        value: "12 in last 30 days",
        insight: "Consistent recent reviews signal active property.",
        recommendation: "Maintain momentum with systematic review generation",
        detailedAnalysis: "You're doing excellent work generating recent reviews - 12 in the past 30 days is above the 8-10 industry benchmark. This recency signals to potential guests that your property is actively managed and current. However, review velocity varies significantly month-to-month (7-18 range), creating inconsistency. Competitors with steady 15+ monthly reviews rank higher in search algorithms. The key is building a systematic, automated process rather than manual, sporadic requests.",
        actionSteps: [
          "Automate review requests to eliminate month-to-month variation",
          "Set minimum target of 15 reviews monthly across all platforms",
          "Create backup request method (SMS) for guests who don't open emails",
          "Track review velocity weekly and adjust tactics accordingly",
          "Ensure all major platforms receive consistent review flow"
        ],
        expectedImpact: "Stabilizing at 15-20 monthly reviews consistently (vs current 7-18 variance) improves search algorithm performance by 12-15%, increasing organic visibility and bookings by $3-5K monthly."
      },
      {
        id: "rep_4",
        name: "Response Rate",
        title: "Response Rate",
        score: 91,
        color: "green",
        label: "Response Rate",
        isLocked: true,
        insight: "Responding to 95% of reviews within 3 days.",
        recommendation: "Aim for 100% responses within 24 hours for competitive edge",
        detailedAnalysis: "You're doing excellent work responding to reviews, significantly better than 68% industry average. However, the 5% you miss are critical - often negative reviews that need immediate attention. Your average response time of 3 days is acceptable but not optimal. Properties responding within 24 hours see 25% more conversions. Guests viewing negative reviews without responses are 40% less likely to book.",
        actionSteps: [
          "Set up review alerts via text/Slack for immediate notification",
          "Create response templates for common scenarios to save time",
          "Assign backup responder for weekends/holidays",
          "Prioritize negative reviews (respond within 6 hours)",
          "Include specific details in responses to show authenticity"
        ],
        expectedImpact: "100% response rate within 24 hours could increase booking conversion by 8-10% among review-sensitive travelers (approximately 30% of your audience), worth $2-3K monthly."
      },
      {
        id: "rep_5",
        name: "Rating Trends",
        title: "Rating Trends",
        score: 79,
        color: "green",
        label: "Rating Trends",
        isLocked: true,
        insight: "Average rating holding steady at 4.3 stars over 6 months.",
        recommendation: "Target 4.5+ rating through service excellence initiatives",
        detailedAnalysis: "Your 4.3-star average is solid but stuck. Competitors have improved from 4.1 to 4.6 in same timeframe while you've remained flat. Analysis shows you're consistently good but rarely exceptional. The gap between 4.3 and 4.5 stars represents a 23% increase in bookings according to TripAdvisor data. Your room cleanliness scores highest (4.7) while service scores lowest (4.0), indicating opportunity for staff training.",
        actionSteps: [
          "Implement guest satisfaction surveys during stay (not just post-departure)",
          "Create service recovery protocol for real-time issue resolution",
          "Launch monthly staff training on hospitality excellence",
          "Set individual staff recognition for 5-star mentions",
          "Add mid-stay check-in calls for multi-night stays",
          "Track and celebrate weekly improvements in specific categories"
        ],
        expectedImpact: "Achieving 4.5+ stars could increase organic visibility by 35%, improve conversion rate by 18-23%, and generate $6-9K additional monthly revenue. Top performers at 4.7+ see 2x booking rates."
      },
      {
        id: "rep_6",
        name: "Platform Distribution",
        title: "Platform Distribution",
        score: 68,
        color: "amber",
        label: "Platform Distribution",
        isLocked: true,
        insight: "Heavy reliance on Google and TripAdvisor, weak on OTA platforms.",
        recommendation: "Balance review distribution across all major booking platforms",
        detailedAnalysis: "Your reviews are concentrated: Google (45%), TripAdvisor (32%), Booking.com (12%), Expedia (8%), Hotels.com (3%). This imbalance hurts OTA rankings where you have fewer reviews. Booking.com and Expedia prioritize properties with consistent recent reviews. Competitors with balanced distribution rank 5-8 positions higher on OTA platforms, where 60% of your bookings originate.",
        actionSteps: [
          "Add platform-specific review requests to post-stay email sequence",
          "Include direct links to each platform's review page",
          "Train staff to mention specific platforms when requesting reviews",
          "Create platform rotation: focus Google (week 1), Booking.com (week 2), etc",
          "Monitor which platforms drive most bookings, prioritize accordingly",
          "Set goal: minimum 10 reviews monthly on each major platform"
        ],
        expectedImpact: "Balanced review distribution could improve OTA rankings by 5-10 positions, increasing visibility and bookings by 25-30% on those platforms. Worth $7-11K additional monthly revenue."
      },
      {
        id: "rep_7",
        name: "Review Quality",
        title: "Review Quality",
        score: 73,
        color: "green",
        label: "Review Quality",
        isLocked: true,
        insight: "Many short reviews lacking detail and keywords.",
        recommendation: "Encourage detailed reviews through strategic prompting",
        detailedAnalysis: "60% of your reviews are under 50 words with generic praise like 'nice hotel' or 'good stay.' Detailed reviews (100+ words) mentioning specific amenities rank higher in search and influence more bookings. Your best reviews mention specific staff names, room features, and experiences. These convert 3x better than short reviews. Competitors are asking specific questions that generate rich, keyword-heavy reviews.",
        actionSteps: [
          "Train staff to create memorable moments guests want to write about",
          "Include 3-4 specific prompts in review requests (e.g., 'How was the breakfast?')",
          "Highlight unique property features in pre-arrival communication",
          "Create shareable moments (signature welcome drink, Instagram-worthy spots)",
          "Respond to detailed reviews with equal detail to encourage others",
          "Share best reviews in staff meetings to inspire excellence"
        ],
        expectedImpact: "Increasing detailed reviews from 40% to 70% could improve SEO rankings, boost conversion rate by 15-20%, and generate $4-6K additional monthly bookings through improved review quality signals."
      },
    ],
  },

  socialMedia: {
    score: 65,
    color: "amber",
    isLocked: false,
    metrics: [
      {
        id: "sm_1",
        name: "Facebook Presence",
        score: 72,
        color: "amber",
        label: "Facebook Presence",
        value: "2,400 followers",
        insight: "Active page but engagement below industry average.",
        recommendation: "Post 3-4x per week with guest photos and local events.",
      },
      {
        id: "sm_2",
        name: "Instagram Presence",
        score: 68,
        color: "amber",
        label: "Instagram Presence",
        value: "1,850 followers",
        insight: "Good visual content but inconsistent posting.",
        recommendation: "Daily Stories + 3 feed posts per week with branded hashtag.",
      },
      {
        id: "sm_3",
        name: "Engagement Rate",
        score: null,
        color: "red",
        label: "Engagement Rate",
        isLocked: true,
      },
      {
        id: "sm_4",
        name: "Content Quality",
        score: null,
        color: "amber",
        label: "Content Quality",
        isLocked: true,
      },
      {
        id: "sm_5",
        name: "Post Frequency",
        score: null,
        color: "amber",
        label: "Post Frequency",
        isLocked: true,
      },
      {
        id: "sm_6",
        name: "Follower Growth",
        score: null,
        color: "green",
        label: "Follower Growth",
        isLocked: true,
      },
    ],
  },

  advertising: {
    score: 58,
    color: "amber",
    isLocked: false,
    metrics: [
      {
        id: "ad_1",
        name: "Google Ads Presence",
        title: "Google Ads Presence",
        score: 48,
        color: "red",
        label: "Google Ads Presence",
        value: "Not detected",
        insight: "No paid search campaigns found.",
        recommendation: "Start with $500/month brand defense + local intent campaign",
        detailedAnalysis: "You're missing out on 300+ high-intent monthly searches in your market. Competitors are spending $2,000-5,000/month on Google Ads and capturing 40% of available demand. Your organic ranking is good (#3-5) but paid ads appear above you, stealing clicks. Even a modest $500/month campaign focusing on brand protection and high-intent keywords ('book hotel [city] tonight') could capture 50-75 incremental bookings monthly.",
        actionSteps: [
          "Set up Google Ads account and conversion tracking",
          "Create brand campaign ($200/month) - immediate priority",
          "Launch local intent campaign ($300/month) targeting transient demand",
          "Use geo-targeting for 15-mile radius around property",
          "Set up remarketing for website visitors (included in budget)",
          "Track ROI weekly and adjust bids based on performance"
        ],
        expectedImpact: "Conservative estimate: $500 monthly spend generates 15-20 bookings at $30-35 cost per acquisition. Revenue: $3,000-4,000 monthly. ROI: 500-700%. Scales profitably up to $2,000/month budget."
      },
      {
        id: "ad_2",
        name: "Meta Ads Presence",
        title: "Meta Ads Presence",
        score: 35,
        color: "red",
        label: "Meta Ads Presence",
        isLocked: true,
        insight: "No Facebook or Instagram advertising active.",
        recommendation: "Test $300/month retargeting campaign for website visitors",
        detailedAnalysis: "Your property has strong visual appeal (based on photos) which performs excellently on Instagram/Facebook. You have 2,400 monthly website visitors but no retargeting campaign to bring them back. Industry data shows retargeting converts at 3-5x higher rate than cold traffic. Competitors are running geo-targeted brand awareness campaigns and stealing share of mind in your market.",
        actionSteps: [
          "Install Meta Pixel on website for retargeting (15 minutes)",
          "Create 5-7 high-quality carousel ads showcasing rooms and amenities",
          "Set up retargeting campaign for website visitors (last 30 days)",
          "Target lookalike audience of past bookers",
          "Run special offer campaigns for shoulder season",
          "A/B test ad creative and audiences monthly"
        ],
        expectedImpact: "$300/month Meta ads could recapture 25-30 lost bookings from website visitors. Revenue impact: $5,000-6,000 monthly. ROI: 1,500-1,900%. Retargeting typically shows positive ROI within first month."
      },
      {
        id: "ad_3",
        name: "Metasearch Visibility",
        title: "Metasearch Visibility",
        score: 41,
        color: "red",
        label: "Metasearch Visibility",
        isLocked: true,
        insight: "Listed on Google Hotel Ads but not optimized.",
        recommendation: "Enable Google Hotel Ads commission program (12% vs 15-20% OTA)",
        detailedAnalysis: "You appear in Google Hotel search but at bottom of results due to no bidding. Metasearch (Google, Trivago, TripAdvisor) drives 25% of all hotel bookings. Your competitors bid $2-4 per click and appear prominently. Google's 12% commission program is cheaper than OTAs (15-20%) and drives more direct bookings. You're missing 50-75 monthly bookings by not participating.",
        actionSteps: [
          "Enable Google Hotel Ads commission program through existing system",
          "Set initial bid at market average ($2.50 per click)",
          "Monitor click-through and conversion rates daily first week",
          "Adjust bids to maintain 4-6x ROI target",
          "Enable free booking links alongside commission model",
          "Add Trivago and TripAdvisor metasearch (month 2)"
        ],
        expectedImpact: "Google Hotel Ads at $400-500/month spend typically generates 25-35 bookings at 12% commission. Net revenue after commission: $5,500-7,500 monthly. More profitable than OTA bookings."
      },
      {
        id: "ad_4",
        name: "Brand Defense",
        title: "Brand Defense",
        score: 45,
        color: "amber",
        label: "Brand Defense",
        isLocked: true,
        insight: "Competitors bidding on your brand name in paid search.",
        recommendation: "Launch defensive Google Ads campaign immediately",
        detailedAnalysis: "Three competitors are actively bidding on '[Your Hotel Name]' searches, appearing above your organic listing. You're losing an estimated 25-30% of brand searches to competitor ads. Cost to defend: $200-300/month. Cost of doing nothing: $2-3K lost revenue monthly. Your brand search volume is 450 searches/month with 65% booking intent. Competitors are spending $1.50-2.50 per click to steal your customers.",
        actionSteps: [
          "Set up Google Ads brand campaign with exact match keywords (priority: critical)",
          "Bid aggressively on your hotel name ($3-5 per click to guarantee top position)",
          "Use ad extensions to take up maximum screen space",
          "Add negative keywords to prevent wasted spend",
          "Set up conversion tracking to measure ROI",
          "Monitor competitor activity weekly and adjust bids"
        ],
        expectedImpact: "Defensive campaign will recapture 80% of lost brand traffic, preventing $2,000-2,400 monthly revenue loss. ROI: 700-800%. Payback period: immediate."
      },
      {
        id: "ad_5",
        name: "Ad Spend Efficiency",
        title: "Ad Spend Efficiency",
        score: 0,
        color: "red",
        label: "Ad Spend Efficiency",
        isLocked: true,
        insight: "No campaigns to measure efficiency.",
        recommendation: "Establish baseline with brand + retargeting ($800/month)",
        detailedAnalysis: "Without any paid advertising, you can't measure or improve efficiency. Starting with high-ROI campaigns (brand defense + retargeting) establishes baseline metrics. Industry benchmarks: Brand campaigns achieve 800-1,200% ROI, retargeting achieves 500-800% ROI, prospecting achieves 200-400% ROI. You should start conservative and scale what works.",
        actionSteps: [
          "Implement conversion tracking across all channels",
          "Start with proven high-ROI channels (brand + retargeting)",
          "Measure cost per acquisition, revenue per booking, ROI weekly",
          "Set target: maintain minimum 400% ROI on blended spend",
          "Scale winners, cut losers monthly",
          "Build 12-month efficiency trend data"
        ],
        expectedImpact: "Starting with $800/month in high-efficiency campaigns should generate $4,000-5,000 monthly revenue (500-625% blended ROI) while building performance data to optimize future spending."
      },
      {
        id: "ad_6",
        name: "Competitor Ad Gaps",
        title: "Competitor Ad Gaps",
        score: 38,
        color: "amber",
        label: "Competitor Ad Gaps",
        isLocked: true,
        insight: "Competitors running 5+ campaigns you're not.",
        recommendation: "Identify and test top 2 competitor strategies",
        detailedAnalysis: "Analysis of competitor ads reveals they're successfully targeting: 1) Last-minute bookings ('hotel tonight' +$2-3/click), 2) Event-based campaigns (concerts, conferences), 3) Weather-triggered ads (unseasonably hot/cold weekends), 4) Day-of-week targeting (Sunday-Thursday business travel), 5) Competitor conquesting (bidding on rival hotel names). These campaigns fill rooms during traditionally slow periods.",
        actionSteps: [
          "Set up event-triggered campaign for major local events",
          "Create last-minute booking campaign (within 24 hours)",
          "Test weather-responsive campaigns (via automated rules)",
          "Launch weekday business traveler campaign",
          "Monitor competitor ad copy and test similar messaging",
          "Analyze which gaps offer highest ROI for your property"
        ],
        expectedImpact: "Filling slow periods with targeted campaigns could add 15-20 incremental bookings monthly during shoulder season, worth $3,000-4,500. Focuses on periods when you need bookings most."
      },
    ],
  },

  booking: {
    score: 75,
    color: "green",
    isLocked: false,
    metrics: [
      {
        id: "bk_1",
        name: "OTA Presence",
        score: 85,
        color: "green",
        label: "OTA Presence",
        value: "Listed on 8 platforms",
        insight: "Strong distribution across major OTAs.",
        recommendation: "Ensure rate parity and current inventory.",
      },
      {
        id: "bk_2",
        name: "Booking.com Profile",
        score: 82,
        color: "green",
        label: "Booking.com Profile",
        value: "8.8/10 rating",
        insight: "Well-optimized with Genius program.",
      },
      {
        id: "bk_3",
        name: "Expedia Profile",
        score: null,
        color: "green",
        label: "Expedia Profile",
        isLocked: true,
      },
      {
        id: "bk_4",
        name: "Direct Booking Flow",
        score: null,
        color: "amber",
        label: "Direct Booking Flow",
        isLocked: true,
        insight: "Unlock to see conversion analysis",
      },
      {
        id: "bk_5",
        name: "Mobile Booking",
        score: null,
        color: "green",
        label: "Mobile Booking",
        isLocked: true,
      },
      {
        id: "bk_6",
        name: "Payment Options",
        score: null,
        color: "green",
        label: "Payment Options",
        isLocked: true,
      },
      {
        id: "bk_7",
        name: "Cancellation Policy",
        score: null,
        color: "amber",
        label: "Cancellation Policy",
        isLocked: true,
      },
    ],
  },

  competitive: {
    score: 71,
    color: "amber",
    isLocked: false,
    metrics: [
      {
        id: "comp_1",
        name: "Market Position",
        score: 68,
        color: "amber",
        label: "Market Position",
        value: "#3 of 12",
        insight: "Solid mid-tier position with room to improve.",
        recommendation: "Focus on unique differentiators to reach #1-2.",
      },
      {
        id: "comp_2",
        name: "Price Competitiveness",
        score: 75,
        color: "green",
        label: "Price Competitiveness",
        value: "$189 average",
        insight: "Well-positioned at 5% below market leader.",
      },
      {
        id: "comp_3",
        name: "Amenity Comparison",
        score: null,
        color: "amber",
        label: "Amenity Comparison",
        isLocked: true,
      },
      {
        id: "comp_4",
        name: "Rating vs Competitors",
        score: null,
        color: "green",
        label: "Rating vs Competitors",
        isLocked: true,
      },
      {
        id: "comp_5",
        name: "Unique Advantages",
        score: null,
        color: "green",
        label: "Unique Advantages",
        isLocked: true,
      },
      {
        id: "comp_6",
        name: "Competitive Threats",
        score: null,
        color: "amber",
        label: "Competitive Threats",
        isLocked: true,
      },
    ],
  },

  competitors: [
    {
      rank: 1,
      name: "Renaissance Chicago Downtown",
      rating: 4.7,
      reviewCount: 1243,
      distance: 0.3,
      lat: 41.8855,
      lng: -87.6235,
      placeId: "ChIJ1234",
      priceLevel: 3,
    },
    {
      rank: 2,
      name: "Hyatt Centric The Loop",
      rating: 4.6,
      reviewCount: 987,
      distance: 0.5,
      lat: 41.8825,
      lng: -87.6295,
      placeId: "ChIJ5678",
      priceLevel: 3,
    },
    {
      rank: 3,
      name: "Grand Plaza Hotel",
      rating: 4.6,
      reviewCount: 847,
      distance: 0,
      lat: 41.8835,
      lng: -87.6245,
      placeId: "ChIJ9012",
      priceLevel: 3,
    },
    {
      rank: 4,
      name: "Aloft Chicago Downtown",
      rating: 4.5,
      reviewCount: 765,
      distance: 0.7,
      lat: 41.8845,
      lng: -87.6275,
      placeId: "ChIJ3456",
      priceLevel: 2,
    },
    {
      rank: 5,
      name: "Kimpton Gray Hotel",
      rating: 4.5,
      reviewCount: 654,
      distance: 0.4,
      lat: 41.8815,
      lng: -87.6285,
      placeId: "ChIJ7890",
      priceLevel: 3,
    },
    // Additional competitors locked behind email gate
    {
      rank: 6,
      name: "Hotel Monaco Chicago",
      rating: 4.4,
      reviewCount: 589,
      distance: 0.6,
      lat: 41.8805,
      lng: -87.6305,
      placeId: "ChIJ1357",
      priceLevel: 3,
    },
    {
      rank: 7,
      name: "Virgin Hotels Chicago",
      rating: 4.4,
      reviewCount: 512,
      distance: 0.8,
      lat: 41.8795,
      lng: -87.6315,
      placeId: "ChIJ2468",
      priceLevel: 3,
    },
    {
      rank: 8,
      name: "The Gwen Hotel",
      rating: 4.3,
      reviewCount: 445,
      distance: 0.9,
      lat: 41.8785,
      lng: -87.6325,
      placeId: "ChIJ3579",
      priceLevel: 3,
    },
  ],

  actionPlan: [
    {
      priority: "high",
      category: "Digital Presence",
      action: "Optimize website speed and mobile performance",
      impact: "Could increase conversions by 15-25% and improve SEO",
      effort: "moderate",
      timeline: "2-4 weeks",
      resources: ["Web developer", "Image optimization tools", "CDN service"],
    },
    {
      priority: "high",
      category: "Advertising",
      action: "Launch Google Ads campaigns for brand + competitor keywords",
      impact: "Expected ROI of 3-5x, capture high-intent searchers",
      effort: "quick-win",
      timeline: "1-2 weeks",
      resources: ["Google Ads budget ($2,000/month)", "PPC specialist"],
    },
    {
      priority: "high",
      category: "Reputation",
      action: "Implement systematic review generation campaign",
      impact: "Increase review volume by 50+ per month, boost SEO",
      effort: "quick-win",
      timeline: "1 week",
      resources: ["Email automation tool", "Review templates"],
    },
    {
      priority: "medium",
      category: "Social Media",
      action: "Establish consistent posting schedule across platforms",
      impact: "Improve engagement by 30-40%, build brand awareness",
      effort: "moderate",
      timeline: "2-3 weeks",
      resources: ["Social media manager", "Content calendar", "Scheduling tool"],
    },
    {
      priority: "medium",
      category: "Booking",
      action: "Simplify direct booking flow and add instant booking",
      impact: "Reduce OTA dependency, increase direct revenue by 10-15%",
      effort: "significant",
      timeline: "4-6 weeks",
      resources: ["Booking engine upgrade", "UX designer", "Developer"],
    },
    {
      priority: "low",
      category: "Competitive",
      action: "Develop unique package offerings to differentiate from competitors",
      impact: "Create pricing power, attract specific segments",
      effort: "moderate",
      timeline: "3-4 weeks",
      resources: ["Revenue manager", "Marketing team", "Package partnerships"],
    },
  ],

  generatedAt: new Date().toISOString(),
  isFullReportUnlocked: false,
};
